name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Application Image
      run: docker build . --file Dockerfile --tag hrittik/sample-flask
    - uses: actions/checkout@v3
    - name: Build Mock Date Image
      run: docker build mock-data/ --file mock-data/Dockerfile --tag hrittik/mock-date
