name: Docker Image CI Build & Push Application

on:
  push:
    branches: [ "master" ]
    paths:
      - 'app/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'app/**'

jobs:
  build_application:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Application Image
      run: docker build . --file Dockerfile --tag hrittik/sample-flask

    - name: Login to DockerHub
      run: docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Application Image to DockerHub
      run: docker push hrittik/sample-flask
